blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://banzaicloud.com/docs/
    about: Check the documentation

  - name: ğŸ’¬ Community Slack
    url: https://slack.banzaicloud.io/
    about: Ping us on Slack if experience any issues with our products

  - name: âœ‰ï¸ Support
    url: https://banzaicloud.com/support/
    about: Check out additional support channels
